#!/usr/bin/env python3
"""
Step 4b: Generate PopART NEXUS file with TRAITS block.
- Groups: Ancient_WJD_Main (Z9850–Z9867) vs Ancient_WJD_Tower (K0909, K0914)
- Excludes LOW coverage samples (Z9853/Z9864) from statistics
- Output: 06_haplo/popart_input.nex
"""
import os
from collections import OrderedDict
from datetime import datetime

BASE = "/mnt/disk2/srtp2024/LIM/IVPP/analysis"
ALIGN_FILE = os.path.join(BASE, "04_align", "final_aln.fasta")
OUT_DIR = os.path.join(BASE, "06_haplo")
LOG_DIR = os.path.join(BASE, "logs")
os.makedirs(OUT_DIR, exist_ok=True)

# ── Read alignment ──
print("=" * 60)
print("Step 4b: Generate PopART NEXUS")
print("=" * 60)
print(f"\n[1/3] Reading alignment: {os.path.basename(ALIGN_FILE)}")

seqs = OrderedDict()
with open(ALIGN_FILE) as f:
    cur_id, cur_seq = None, []
    for line in f:
        line = line.strip()
        if line.startswith(">"):
            if cur_id:
                seqs[cur_id] = "".join(cur_seq)
            cur_id = line[1:].split()[0]
            cur_seq = []
        else:
            cur_seq.append(line.upper())
    if cur_id:
        seqs[cur_id] = "".join(cur_seq)

# Retain only Wenjiangduo samples
wjd_ids = [sid for sid in seqs if not any(
    prefix in sid for prefix in ["MOD_", "LIT", "CORE_", "REF_", "all_combined"]
)]
wjd_seqs = OrderedDict((sid, seqs[sid]) for sid in wjd_ids)
aln_len = len(list(wjd_seqs.values())[0])

print(f"  WJD samples: {len(wjd_seqs)}")

# ── Define TRAITS groups from SAMPLE_META.md ──
TRAITS = OrderedDict([
    ("Ancient_WJD_Tower", {"K0909", "K0914"}),
    ("Ancient_WJD_Main", {"Z9850", "Z9851", "Z9852", "Z9853", "Z9854", "Z9855",
                           "Z9856", "Z9857", "Z9858", "Z9859", "Z9860", "Z9861",
                           "Z9863", "Z9864", "Z9865", "Z9867"}),
])

# Build reverse lookup: taxon -> group
taxon_group = {}
for group, members in TRAITS.items():
    for sid in members:
        taxon_group[sid] = group

# ── Write NEXUS ──
print(f"\n[2/3] Writing NEXUS file...")

nex_path = os.path.join(OUT_DIR, "popart_input.nex")
with open(nex_path, "w") as f:
    f.write("#NEXUS\n\n")
    f.write(f"[Generated by step4_to_nexus.py at {datetime.now().strftime('%Y-%m-%d %H:%M')}]\n")
    f.write("[Step 4b: PopART input for Wenjiangduo haplotype network]\n\n")

    # TAXA block
    f.write("BEGIN TAXA;\n")
    f.write(f"  DIMENSIONS NTAX={len(wjd_seqs)};\n")
    f.write("  TAXLABELS\n")
    for sid in wjd_ids:
        f.write(f"    {sid}\n")
    f.write("  ;\n")
    f.write("END;\n\n")

    # CHARACTERS block
    f.write("BEGIN CHARACTERS;\n")
    f.write(f"  DIMENSIONS NCHAR={aln_len};\n")
    f.write("  FORMAT DATATYPE=DNA MISSING=? GAP=-;\n")
    f.write("  MATRIX\n")
    for sid in wjd_ids:
        seq = wjd_seqs[sid]
        # Split long sequences into chunks of 80 bp
        chunks = [seq[i:i+80] for i in range(0, len(seq), 80)]
        f.write(f"    {sid}\n")
        for chunk in chunks:
            f.write(f"    {chunk}\n")
    f.write("  ;\n")
    f.write("END;\n\n")

    # TRAITS block (PopART coloring)
    f.write("BEGIN TRAITS;\n")
    f.write("  DIMENSIONS NTRAITS=1;\n")
    f.write("  FORMAT LABELS=YES MISSING=?;\n")
    f.write("  TRAIT SEPARATOR=Space;\n")
    f.write("  TAXA\n")
    for sid in wjd_ids:
        group = taxon_group.get(sid, "Unknown")
        f.write(f"    {sid} {group}\n")
    f.write("  ;\n")
    f.write("END;\n")

print(f"  NTAX (sequences): {len(wjd_seqs)}")
print(f"  NCHAR (sites):    {aln_len} bp")
print(f"  TRAITS groups:    {len(TRAITS)}")

# ── Summary ──
print(f"\n[3/3] Summary")
tower_ids = TRAITS["Ancient_WJD_Tower"]
main_ids = TRAITS["Ancient_WJD_Main"]
print(f"\n{'='*60}")
print("TRAITS GROUP SUMMARY")
print(f"{'='*60}")
for group, members in TRAITS.items():
    print(f"  {group}: {len(members)} samples — {', '.join(sorted(members))}")

# Excluded from stats
print(f"\n  LOW coverage (excluded from stats, but retained in NEXUS):")
print(f"    Z9853 (2.1×) — Ancient_WJD_Main")
print(f"    Z9864 (10.9×) — Ancient_WJD_Main")

print(f"\nOutput: {nex_path}")
print(f"{'='*60}")
print("DONE")
print(f"{'='*60}")